const siteMetaData = {
  keywords: [
    'unsubscribe',
    'privacy',
    'unsubscribe me',
    'stop spam emails',
    'how to unsubscribe',
    'stop newsletter',
  ],
  title: 'Unsub',
  titleAlt: 'Unsub | Take back control of your email',
  description: 'See the emails you want. Get rid of the rest automagically.',
  url: 'https://www.unsub.email//',
  siteUrl: 'https://www.unsub.email//',
  siteLanguage: 'en-US',
  logo: 'https://www.unsub.email/',
  image: 'https://www.unsub.email/',
  favicon: '/favicon.ico',
  shortName: 'Unsub',
  author: '_Heyglassy',
  themeColor: '#000000',
  backgroundColor: '#ffffff',
  twitterDesc: 'See the emails you want. Get rid of the rest automagically',
  twitter: 'https://twitter.com/_heyglassy',
  locale: 'en-US',
  ogLanguage: 'en_US',
}
export default siteMetaData
